laba1_MVC/Models/OperandsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace laba1_MVC.Models
{
    public class OperandsModel
    {
        public int x { get; set; }
        //public int[] arr { get; set; }
        public string toArr { get; set; }
    }
}

laba1_MVC/Controllers/FindController.cs
using laba1_MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace laba1_MVC.Controllers
{
    public class FindController : Controller
    {
        // GET: Find
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(OperandsModel model)
        {
            string result = string.Empty;
            List<string> arrAllString = model.toArr.Split(' ').ToList();
            List<int> arrAll = new List<int>();
            List<int> arr2 = new List<int>();
            List<string> newResult = new List<string>();
            try
            {
                for(int i = 0; i < arrAllString.Count; i++)
                {
                    arrAll.Add(int.Parse(arrAllString[i]));
                }
                for (int i = 0; i < arrAll.Count; i++)
                {
                    if (arrAll[i] == model.x)
                    {
                        arr2.Add(i);
                    }
            
                  
                }
                for(int i = 0; i < arr2.Count; i++)
                {
                    newResult.Add($"Number {model.x} stays in position {arr2[i] + 1} ");
                }

                result = newResult.Aggregate((curr, next) => curr + ", " + next);
            }
            catch (Exception e)
            {
                result = "Error: " + e.Message.ToString();
            }
            ViewBag.Result = result;
            return View();
        }
    }
}

laba1_MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace laba1_MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

laba1_MVC/Views/Find/Index.cshtml
@model laba1_MVC.Models.OperandsModel

@{ 
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Index", "Find"))
        {
            <p>Enter x what you want to find:</p>
            @Html.TextAreaFor(x => x.x);
            //@{
            //    string temp="";
            //
            //    for(int i=0; i < ; i++)
            //    {
            //
            //    }
            //}

            //<td>@Html.TextArea("Array input", temp, new { id = "Array" });</td>

            //for (int i = 0; i < Model.arr.Length; i++)
            //{
            //    <p>Number (@(i+1)) : </p>
            //    @Html.EditorFor(x => x.arr[i]);
            //}
            //@Html.TextAreaFor(x => x.numbOfElements);

            <p>Enter the array by white space: </p>
            @Html.TextAreaFor(x => x.toArr);
            

            <input type="submit" value="Find" />
        }
    </div>
    @if(!string.IsNullOrWhiteSpace(ViewBag.Result))
    {
        <p>@ViewBag.Result</p>
    }
</body>
</html>